# Use the official Python image for Python 3.12
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . /app/

# Expose the Daphne server port
EXPOSE 8000

# Run Daphne ASGI server
CMD ["sh", "-c", "daphne -b 0.0.0.0 -p 8000 xAnalysisBackend.asgi:application & python manage.py run_consumer --num_workers 3"]
