# Generated by Django 5.1.3 on 2024-11-15 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('embeddings', models.JSONField()),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('unique_identifier', models.CharField(max_length=64, unique=True)),
                ('keywords', models.ManyToManyField(related_name='tweets', to='TweetProcessor.keyword')),
            ],
        ),
    ]
