# Generated by Django 5.1.3 on 2024-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetProcessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
